version: '3.8'
services:
  dynamodb:
    image:  amazon/dynamodb-local
    container_name: dynamodb-local
    restart: always
    environment:
        AWS_ACCESS_KEY_ID: root
        AWS_SECRET_ACCESS_KEY: pass
        AWS_REGION: us-east-1
    volumes:
      -  ./.dynamodb-data:/home/dynamodblocal/data
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
  dynamodb-admin:
    image: aaronshaf/dynamodb-admin
    container_name: dynamodb-admin
    ports:
      - "8001:8001"
    environment:
      DYNAMO_ENDPOINT: "http://dynamodb-local:8000"
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: root
      AWS_SECRET_ACCESS_KEY: pass
    depends_on:
      - dynamodb-local